### ISSUE TITLE
WebIDE won't connect to RPi

### ISSUE THREAD

**Issue by lanternmakers** [adafruit/Adafruit-WebIDE#117]
Hi!
I'm having the same problem with every version of WebIDE: it gets stuck at "Checking Editor Health" for a _very_ long time, then writes "Attempting to reconnect" in the upper right corner.

My laptop runs Win7, and is connected via Wifi. I have tried both Firefox and Chrome with the same result.

My Pi has pristine Occidentalis 0.2 installed and is connected to the internet box via ethernet.

I can connect to the RPi from the laptop using PuTTY. The WebIDE curl install commands work, so I guess the RPi can access the internet.

I tried the commands that you suggest in another topic ( 
sudo pkill restartd
sudo pkill node
sudo -u webide -g webide node server

with the following result:
git push queue init
REPOSITORY_PATH /usr/share/adafruit/webide/repositories
info: Logger initialized!
   info  - socket.io started
webdav filesystem mounted

http://raspberrypi.local/auth/bitbucket/callback
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:32 GMT] "GET / HTTP/1.1" 302 70 "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:33 GMT] "GET /editor HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /stylesheets/font-awesome.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /stylesheets/bootstrap.min.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /stylesheets/app.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /stylesheets/colorbox.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/fileupload/css/jquery.fileupload-ui.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/jquery.min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /stylesheets/pytutor.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /style.css HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/trace/d3.v2.min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/ace/ace.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /tty.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /term.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/trace/jquery.ba-bbq.min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/trace/pytutor.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/trace/jquery.jsPlumb-1.3.10-all-min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /options.js HTTP/1.1" 200 881 "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/fileupload/js/jquery.fileupload.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/fileupload/js/vendor/jquery.ui.widget.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/davFS.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/fileupload/js/jquery.fileupload-ui.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/later/later-recur.min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/jquery.colorbox-min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:34 GMT] "GET /javascripts/later/later.min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:38 GMT] "GET /javascripts/occ_editor.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:38 GMT] "GET /javascripts/webide_utils.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:38 GMT] "GET /javascripts/context_menu.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:38 GMT] "GET /images/WebIDE_Logo_Alpha@2x.png HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:38 GMT] "GET /javascripts/bootstrap.min.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:39 GMT] "GET /javascripts/ace/theme-merbivore_soft.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:39 GMT] "GET /javascripts/ace/mode-python.js HTTP/1.1" 304 - "http://raspberrypi.local/editor" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
192.168.0.34 - - [Fri, 18 Jan 2013 21:39:39 GMT] "GET /favicon.ico HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
[tty.js] 0 Session 0 created.

Then nothing...
I have disabled my firewall with no success.

What more can I try to find a solution?

Thomas

**Comment by fdominguezr** [comment]
Hi!

I can't access to the WebIDE that is in my Raspberry Pi B+, with my Google Chrome.
I tried with both http://raspberrypi.local and http://xx.xx.xx.xx where the x's are replaced with your Pi's IP address.
The message I get is: ERR_CONNECTION_REFUSED
I tried to installa manually as hermannw said but I had the same problem.

Any idea? Thanks!

**Comment by dpakman** [comment]
WebIDE just does not work. I have a fully functioning Raspberry Pi B+ with functional new 32G microSD card. Installed raspian Jessie Nov 2015 version, used Adafruit Pi Finder to install all tools and WebIDE. Can SSH to RPi perfectly. And can connect to WebIDE via Mac Chrome Web browser. But WebIDE hangs on "Checking Editor Health". This has nothing to do with Avast. I am on a Mac and have no antivirus. In addition, websockets are accessible and working fine (http://websocketstest.com/).

Can you help? Does this IDE work for anyone? Can't find anyone successfully using it...

**Comment by jwcooper** [comment]
Right now the default installation is only working on the Raspberry Pi 2. This is due to the node binary being included with the Pi only being compatible with the armv7 chipset. You'll  need to manually install node 0.10.x if you're not using a Pi 2 until we can fix it or get a pull request with a fix.

**Comment by dpakman** [comment]
Thanks for the response. Many RPi users have trouble getting node successfully installed, particularly older versions such as 0.10.x. Can you suggest a method which will work with your IDE?

**Comment by jwcooper** [comment]
Yea, you may have another issue entirely. Check the /usr/share/adafruit/webide/logs folder to see what errors you're getting.

**Comment by dpakman** [comment]
I am getting the error below. But after doing a simple apt-get update and apt-get upgrade, I can't even connect to the IDE now, same errors other had.

2016-01-18T15:50:49.309Z - error: uncaughtException date=Mon Jan 18 2016 10:50:49 GMT-0500 (EST), pid=11969, uid=1001, gid=1001, cwd=/, execPath=/usr/share/adafruit/webide/bin/node_hf/node, version=v0.10.29, argv=[/usr/share/adafruit/webide/bin/node_hf/node, /usr/share/adafruit/webide/server.js], rss=44146688, heapTotal=34978176, heapUsed=19505092, loadavg=[0.8505859375, 0.5068359375, 0.47265625], uptime=1770.209592781, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=338, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=280, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=25, file=/usr/share/adafruit/webide/server.js, function=SocketNamespace.auth, line=387, method=auth, native=false, column=15, file=/usr/share/adafruit/webide/node_modules/socket.io/lib/namespace.js, function=SocketNamespace.authorize, line=245, method=authorize, native=false, column=14, file=/usr/share/adafruit/webide/node_modules/socket.io/lib/namespace.js, function=SocketNamespace.handlePacket, line=302, method=handlePacket, native=false, column=32, file=/usr/share/adafruit/webide/node_modules/socket.io/lib/manager.js, function=Manager.handleClient, line=697, method=handleClient, native=false, column=8, file=/usr/share/adafruit/webide/node_modules/socket.io/lib/manager.js, function=Manager.handleUpgrade, line=618, method=handleUpgrade, native=false, column=10, file=/usr/share/adafruit/webide/node_modules/socket.io/lib/manager.js, function=, line=123, method=null, native=false], stack=[Error: Cannot find module 'cookie',     at Function.Module._resolveFilename (module.js:338:15),     at Function.Module._load (module.js:280:25),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at SocketNamespace.auth (/usr/share/adafruit/webide/server.js:387:25),     at SocketNamespace.authorize (/usr/share/adafruit/webide/node_modules/socket.io/lib/namespace.js:245:15),     at SocketNamespace.handlePacket (/usr/share/adafruit/webide/node_modules/socket.io/lib/namespace.js:302:14),     at Manager.handleClient (/usr/share/adafruit/webide/node_modules/socket.io/lib/manager.js:697:32),     at Manager.handleUpgrade (/usr/share/adafruit/webide/node_modules/socket.io/lib/manager.js:618:8),     at Server.<anonymous> (/usr/share/adafruit/webide/node_modules/socket.io/lib/manager.js:123:10)]

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
