### ISSUE TITLE
Selectively ignore files

### ISSUE THREAD

**Issue by leomoty** [adafruit/Adafruit-WebIDE#118]
I'd like to know if it is possible to/or add a feature that ignores certain kinds of files, something like gitignore.

Example:
I'd compile my mono projects using terminal and then there is whatever.exe, so if i config a file for directory or else, all *.exe would be unlisted on the editor.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
