### ISSUE TITLE
In debug mode cant use raw_input

### ISSUE THREAD

**Issue by bbkiwi** [adafruit/Adafruit-WebIDE#131]
Running the following in debug mode gets an error (maybe because there is no terminal window available in which to type input)

``` #!/usr/bin/python
while 1:
    str = raw_input("Give me input!")
    print str   
```

gives this Debug output

  Give me input!Traceback (most recent call last):
  File "debugger.py", line 314, in start_debug
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 387, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/usr/share/adafruit/webide/repositories/my-pi-projects/Adafruit_CharLCDPlate/Bug1.py", line 3, in <module>
    while 1:
AttributeError: Debugger instance has no attribute 'readline'
--- Program Exited with an Exception ---

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
