### ISSUE TITLE
Request improvement of step-in debug mode

### ISSUE THREAD

**Issue by bbkiwi** [adafruit/Adafruit-WebIDE#135]
Hi Justin, You've done a great job. One feature that would be very helpful is when using step-in, is for the edit window to switch to the appropriate file when the code be executed comes from imported classes. Thanks.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
