### ISSUE TITLE
Debugger bug

### ISSUE THREAD

**Issue by bbkiwi** [adafruit/Adafruit-WebIDE#148]
Hi Justin, 

When stepping over, this code screws up the debugger. 

``` python
#!/usr/bin/python
gamma = bytearray(2)
gamma[1] = 0x80
print gamma[1]
```

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
