### ISSUE TITLE
Edit text sometimes black on white

### ISSUE THREAD

**Issue by bbkiwi** [adafruit/Adafruit-WebIDE#149]
Hi Justin, 

   Sometimes lately the text in the editor is on a white background with dark text, and then at some point changes to white on dark background. Can't see any pattern as to when is happens. Is this a new feature :-)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
