### ISSUE TITLE
Stuck at "Initializing Editor..."

### ISSUE THREAD

**Issue by perjg** [adafruit/Adafruit-WebIDE#165]
I've installed webIDE on my RPi using the method described here:
Fresh installation of webIDE (with bitbucket set up, and logged in).

The next screen after logging in always gets stuck at "Initializing Editor..."

Chrome dev tools shows:

Uncaught SyntaxError: Unexpected Token (
javascripts/ace/ace.js:1

(called from occ_editor.js:113)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
