### ISSUE TITLE
Support for python 3

### ISSUE THREAD

**Issue by jwcooper** [adafruit/Adafruit-WebIDE#176]
Create setting to customize the execute command for python.

**Comment by lucasstinis** [comment]
I want to +1 this! It took me a while to notice that the errors I was getting when running my code were due to the version of Python being run. I want to use WebIDE to teach kids how to program using Python. The IDE is great for that, but python 3 offers a much more beginner friendly experience.

**Comment by hedrickbt** [comment]
Is there support for python3 yet?

**Comment by sabas1080** [comment]
Is there support for python3 yet?

**Comment by M-Gjerde** [comment]
When will python3 available?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
