### ISSUE TITLE
Scheduled job parser getting intervals wrong

### ISSUE THREAD

**Issue by Slugsie** [adafruit/Adafruit-WebIDE#179]
WebIDE v0.3.6
Wheezy 2013-02-09

I'm trying to schedule a Python script to run "every 1 hour". The Job scheduler accepts that, and that is how it appears in the Schedule manager. However the script actually runs every minute. Similarly if I schedule it for "every 2 hours", it still runs every minute.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
