### ISSUE TITLE
WebIDE Konsole Problem - too thin

### ISSUE THREAD

**Issue by Steakschen** [adafruit/Adafruit-WebIDE#182]
Hello,

is there any chance to enerlage the Konsole to the right side.

I cant see the last line because the text is too long.
I only see something like 60 letters a line but i "could" have something like 140 

How to make it bigger?
Hope you know what i mean 
![adafruit](https://f.cloud.github.com/assets/3679092/317519/35b942b4-9875-11e2-9794-d0ad5b8180c1.jpg)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
