### ISSUE TITLE
editing file in WebIDE gives indentation error

### ISSUE THREAD

**Issue by Juggler00** [adafruit/Adafruit-WebIDE#187]
I just upgraded to v0.3.7 of your WebIDE. Whenever I try to add a line to my python program, I now receive an "IndentationError: unexpected ident". I've tried this with both Chrom and Safari–same result.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
