### ISSUE TITLE
Angstrom install - default My-Pi-Projects overwrites what's already on BitBucket's repository

### ISSUE THREAD

**Issue by monsieurDavid** [adafruit/Adafruit-WebIDE#199]
After installing and getting the WebIDE to work on Angstrom, the default My-Pi-Projects has deleted the many files that already were in this repository on my BitBucket account.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
