### ISSUE TITLE
Can't use a separate Bitbucket repository for BeagleBone 

### ISSUE THREAD

**Issue by quantalume** [adafruit/Adafruit-WebIDE#203]
I've successfully built the WebIDE on a BeagleBone Black running Angstrom. The WebIDE loads properly on port 8080 (port 80 is already used by the BBB), and I can connect properly to Bitbucket. The problem however is that WebIDE is very Pi-centric. If I create a new repository on Bitbucket, the WebIDE doesn't recognize it, and of course all the code in the Adafruit-Raspberry-Pi and my-pi-projects repositories is of no use on the BeagleBone. I can use the WebIDE to write some Python code, but I don't really want to save it to my-pi-projects, and I can't create a new repository and have it recognized by WebIDE.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
