### ISSUE TITLE
BBB - No connect to WebIDE after install with latest Angstrom (5-20-13) image

### ISSUE THREAD

**Issue by Maddox-zephyr** [adafruit/Adafruit-WebIDE#207]
The install goes smoothly and says WebIDE is started, but I've tried both the 80 port and the 8080 ports and can't connect. From below, it looks like it is running.  I tried uninstall and reinstall with same result (if at first you don't succeed, try, ....)

Any thoughts or other info I can provide?
# ps aux | grep webide

root       130  0.0  0.2   4344  1452 ?        Ss   Jan01   0:00 /usr/bin/sudo -u webide -g webide /usr/bin/node /usr/share/adafruit/webide/server.js
webide     280  0.0  4.9  66288 25036 ?        Sl   Jan01   0:23 /usr/bin/node /usr/share/adafruit/webide/server.js
root       789  1.0  0.1   1960   612 pts/0    S+   16:44   0:00 grep webide
root@bigbone:~# sudo service adafruit-webide.sh stop

**Comment by KrishnaPG** [comment]
Any solution for this - encountering the same problem.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
