### ISSUE TITLE
"user-agent-required" error when loging with github account

### ISSUE THREAD

**Issue by pierre2mars** [adafruit/Adafruit-WebIDE#208]
Hi,
I tried to setup webide with a github account. 
I registered a new application in my GitHub account with the following parameters:
name: raspberrypi_web_ide 
url: http://raspberrypi.local/login
uri: http://raspberrypi.local/auth/github/callback
When I open the webide address (raspberrypi.local/login), I get the "click here to login to your github account" button, If press it I get the following error:
failed to fetch user profile (status: 403 data: {"message":"Missing or invalid User Agent string. See http://developer.github.com/v3/#user-agent-required"})
Do you have any idea of what I am missing here?

best regards,

Pierre

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
