### ISSUE TITLE
Fresh install on raspi gives no success with different OSs

### ISSUE THREAD

**Issue by technogeek48** [adafruit/Adafruit-WebIDE#211]
Installing WebIde in raspian or occidentalis is working perfectly, installer reports that service is running. But when i navigate to http://raspberrypi.local/ the browser does not connect.

I did this as troubleshooting:
sudo service adafruit-webide stop
sudo service adafruit-webide start   #and i get the following error:
Failed to set capabilities on file `/usr/share/adafruit/webide/bin/node_hf/node' (Operation not supported)

ALSO:
pi@raspberrypi ~ $ sudo pkill -u webide
pi@raspberrypi ~ $ sudo -u webide -g webide node server #i get this error:

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module '/home/pi/server'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:39)

I saw another issue similar to mine on a beaglebone black. If anyone could help me i would really appreciate it as i have been trying to install the WebIde on my PI for two days now.

Specs:
Raspberry Pi Model B
   WiPi wifi module
   Occidentalis 0.2 and Raspian wheezy with same results
   BerryBoot as bootloader

=====EDIT=====
After days of troubleshooting i just removed berryboot and use N00BS from the pi website. Seems to be working now.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
