### ISSUE TITLE
Cannot start Visualizer, missing '' in sys.path

### ISSUE THREAD

**Issue by mornil** [adafruit/Adafruit-WebIDE#212]
I clone Adafruit_LEDBackpack and can run and debug ex_7segment_clock.py.
When I click on Visualize I get a red cross in the editor which says:

ImportError: No module named Adafruit_7Segment

If I remote debug /usr/share/adafruit/webide/helpers/python/encoder_combined.py I see that '' (empty string, current directory) is missing from sys.path. Adding sys.path.append('.') at the top (before comments) in encoder_combined.py makes the Visualizer work again.

I know that I have tried the WebIDE before I reinstalled Raspbian, and then I did not have to make this fix.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
