### ISSUE TITLE
Schedule Manager disabled when IDE disconnected

### ISSUE THREAD

**Issue by squilter** [adafruit/Adafruit-WebIDE#214]
I have a python script set in the schedule manager to "every 2 minutes".  It does in fact run every two minutes, but only when the IDE is connected.  If I turn off my pc or close the tab, it won't run anymore.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
