### ISSUE TITLE
Arduino upload from webide

### ISSUE THREAD

**Issue by kghunt** [adafruit/Adafruit-WebIDE#220]
The ability to upload and arduino sketch to an arduino or atmega chip attached to the rasberry pi. like the gertboard or the paperduino-pi. Or just simply an uno or mini.

Most of the core components are there for uploading sketches using the shell etc.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
