### ISSUE TITLE
Would it b possible to translate WebIDE interface to another langage?

### ISSUE THREAD

**Issue by mchobby** [adafruit/Adafruit-WebIDE#222]
We are documenting the WebIDE in french to promote it as development plateform for Raspberry Pi.
It would be really awesome to have the WebIDE interface in French (directly translated from the WebIDE root sources would be the best).

Let me know if this is possible and how to help for this task.

Kind regards,
Dominique
MCHobby.be

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
