### ISSUE TITLE
Saved my first file and it produced error "Failure adding file to Git"

### ISSUE THREAD

**Issue by bethesdamd** [adafruit/Adafruit-WebIDE#229]
It's possible I overlooked something in the install...?

**Comment by M-Klitgaard** [comment]
Same here files not showing up on Bitbucket...
The new relase of Adafruit is somehow very fragile and not working.... very frustrating!!!

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
