### ISSUE TITLE
Not saving files

### ISSUE THREAD

**Issue by AThomsonSMC** [adafruit/Adafruit-WebIDE#230]
I just got this set up, and tried to start using it but files simply won't save.  If I do editing through the terminal, a refresh will pick the changes up, but any changes I make through WebIDE don't hold.  After hitting the save button, the file becomes inaccessible for about 2 minutes, and when it reopens eventually, it has no changes saved.  Not sure if it makes a difference, but I'm using django.  Not sure what other information to provide, but I can get it if I know what I'm looking for.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
