### ISSUE TITLE
wifi change-script

### ISSUE THREAD

**Issue by m3corporation** [adafruit/Adafruit-WebIDE#233]
hi

on my pi the wifi change script doesnt work, until i use the {} for the $1 variable:
so i changed to ${1} and now the script works perfect.

 sed -i.bak "/ssid/s/\"([^\"]*)\"/\"${1}\"/"  /etc/network/interfaces

michael

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
