### ISSUE TITLE
Can't create/upload files in repository root

### ISSUE THREAD

**Issue by selectnone** [adafruit/Adafruit-WebIDE#236]
It is not possible to create/upload a file into the root-folder of a repository - there's just a 'Create Project Folder' button.

I've just noticed this after cloning a single-project repository with files in the root (instead of using the default 'my-pi-projects' repository, which expects per-project folders)

**Comment by selectnone** [comment]
I see this is still the case - if I want to add files to the root-folder of a repository, I have to do it outside of the WebIDE, which I can never remember how to do...

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
