### ISSUE TITLE
Error siging into WebIDE

### ISSUE THREAD

**Issue by paw376** [adafruit/Adafruit-WebIDE#238]
I've just configured webIDE on an rPi running Occidentalis v0.2. I created a BitBucket account and was able to log in to the rPi WebIDE to get the OAuth key and secret (which I placed in the BitBucket Integrated Applications section). However, once I completed this process, I can no longer access the rPi via the WebIDE URL. I get the following message:

There was an error signing in. It could be any number of reasons, but first ensure that your date/time is set accurately on your Pi. For More help, visit the FAQ for assistance.

To try and repair the error, by setting your date and time, click the below link. You will be redirected to the login page after 5-10 seconds to try login in again.

Set the Date and Time

failed to obtain request token (Error: socket hang up) 

Does anyone have any idea what I've done wrong?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
