### ISSUE TITLE
Ability to change the colour scheme of the WebIDE

### ISSUE THREAD

**Issue by hp-bioing** [adafruit/Adafruit-WebIDE#243]
Hi folks,

would be great, if it would be possible to change the colour scheme of the WebIDE. This white on blank isn't the best for my eyes. Is there any change to mod a config file for adjusting the colours?

Thank you

hp-bioing

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
