### ISSUE TITLE
Cursor in editor window is off by one character

### ISSUE THREAD

**Issue by ClintonKeith** [adafruit/Adafruit-WebIDE#244]
Using 0.3.8 in Safari on a Mac w OS 10.9.  When in the editing window, the cursor is off by one character to the right.  The two shots below show the cursor position just before and after I type the letter 'T' into the window. 

![2](https://f.cloud.github.com/assets/4081423/1784411/9822c24e-68d2-11e3-8adb-7166f58b1fff.png)
![1](https://f.cloud.github.com/assets/4081423/1784412/9825fbc6-68d2-11e3-95df-c9f8bcc5042a.png)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
