### ISSUE TITLE
WebIDE on iPad

### ISSUE THREAD

**Issue by rwreynolds** [adafruit/Adafruit-WebIDE#245]
OK, this is not really an issue, more of a workaround to issue #50. I know this may seem a little crazy but it works, and let's me work from my iPad quite nicely. Thought it might help someone. 

Here's what I did....
1) Setup WebIDE on my Pi
2) Setup VNC on my iPad (viewer) and Windows 7 laptop (server)
2) Access the IDE from my laptop.
3) VNC from the iPad to the laptop.

I know have access to my WebIDE from my iPad with full keyboard control. I use a BT keyboard with my iPad so I really have a full keyboard. Works great!

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
