### ISSUE TITLE
WebIDE will not install

### ISSUE THREAD

**Issue by ZakEspley** [adafruit/Adafruit-WebIDE#246]
I am running Raspbian Wheezy

I have tried the auto installation and the manual installation and I can not get either one to work. 

<code> Reading package lists... Done
Building dependency tree  
Reading state information... Done
avahi-daemon is already the newest version.
git is already the newest version.
i2c-tools is already the newest version.
libcap2-bin is already the newest version.
python-smbus is already the newest version.
redis-server is already the newest version.
restartd is already the newest version.
The following packages were automatically installed and are no longer required:
  ax25-node libax25 openbsd-inetd
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  nodejs nodejs-legacy
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5,024 kB of archives.
After this operation, 127 kB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 74601 files and directories currently installed.)
Unpacking nodejs (from .../nodejs_0.10.12_armhf.deb) ...
Unpacking nodejs-legacy (from .../nodejs-legacy_0.6.19~dfsg1-6_all.deb) ...
dpkg: error processing /var/cache/apt/archives/nodejs-legacy_0.6.19~dfsg1-6_all.deb (--unpack):
 trying to overwrite '/usr/bin/node', which is also in package nodejs 0.10.12
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs-legacy_0.6.19~dfsg1-6_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
</code>

from the manual installation process,

<code>Reading package lists... Done
Building dependency tree  
Reading state information... Done
build-essential is already the newest version.
git is already the newest version.
redis-server is already the newest version.
nodejs is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Breaks: npm but 1.1.4~dfsg-2 is to be installed
 npm : Depends: nodejs-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
</code>

The problem has something to do with node, nodejs, nodejs-legacy, and npm but I have no idea what. I have tried installing them independently with apt-get but I get errors every time. I am not sure what I need to do or if it is possible for me to install it.

I've also tried installing Node manually and then the manual process minus the nodejs, node-legacy, and npm bits but then when I tried to run the last line, 

<code>nodejs server.js</code> 

I got,

<code>-bash: nodejs: command not found</code>

I lastly tried uninstalling node, nodejs, and npm and running both styles of installations and received the same errors.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
