### ISSUE TITLE
WebIDE - Chrome - file list does not update

### ISSUE THREAD

**Issue by anagram** [adafruit/Adafruit-WebIDE#247]
the file list in the IDE doesn't update after I select a directory. (In terminal, it has changed directory.)

If I click directory name again, terminal shows a cd into the same directory name, then complains 'no such directory'

TERMINAL:
webide@raspberrypi /usr/share/adafruit/webide/repositories/my-pi-projects/Debugging $ cd /usr/share/adafruit/webide/repositories/my-pi-projects/Debugging/Debugging  
bash: cd: /usr/share/adafruit/webide/repositories/my-pi-projects/Debugging/Debugging: No such file or directory

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
