### ISSUE TITLE
Firefox in OSX 10.9.1 Mavericks - File list doesn't update, icons don't render.

### ISSUE THREAD

**Issue by anagram** [adafruit/Adafruit-WebIDE#248]
Firefox browser running OSX 10.9.1 Mavericks: 

Clicking on file or directory only works sometimes.
Sometimes the terminal reports a directory change, but the IDE still shows old directory. Clicking the desired directory name again, causes error message in terminal:

webide@raspberrypi /usr/share/adafruit/webide/repositories/my-pi-projects $ cd /usr/share/adafruit/webide/repositories/my-pi-projects/my-pi-pr
ojects                                                                                                                                        
bash: cd: /usr/share/adafruit/webide/repositories/my-pi-projects/my-pi-projects: No such file or directory    

Also, icons missing:

![texteditscreensnapz003](https://f.cloud.github.com/assets/86141/1906409/8e93910e-7caf-11e3-9df2-31d29d527eef.jpg)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
