### ISSUE TITLE
Schedule manager hidden after clicking settings

### ISSUE THREAD

**Issue by squilter** [adafruit/Adafruit-WebIDE#249]
After clicking my username to access the settings page, I cannot view the schedule manager any more.  Clicking schedule manager will show me my settings again.  I have to refresh the page before the schedule manager does what it's supposed to again.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
