### ISSUE TITLE
Setting up Adafruit WedIDE with Github Account

### ISSUE THREAD

**Issue by pwclab** [adafruit/Adafruit-WebIDE#254]
Hi, I'm trying to get everything set up with Github instead of Bitbucket. At http://raspberrypi.local/setup I am asked for a "key" and "secret". 

I created my RSA key on the PI, added it to Github and added it at  http://raspberrypi.local/setup. 

In order to add a "secret" I guess I need to add an Application to Github which asks me for a "Homepage URL" and "Authorization callback URL". I set both of these to http://raspberrypi.local. This provided me a "secret" which I added to http://raspberrypi.local/setup. 

When I press Submit I get "Settings Successfully Configured." but when I then click "click here to log in to your Github Account", I get a 404 Page Not found. 

I'm not sure what to try next. Anyone have any tips on what I am doing wrong?

**Comment by carlosperate** [comment]
I am in the same boat here, I was able to get to the edit updating passport github to 0.1.5 and then every time I load the WebIDE to dies as soon as the editor is displayed (after showing all the "loading..." data):

```
[tty.js] 1 Session 1 created.
false
self-check-complete
check_for_updates
get_version_info
getting settings { enable_make: 'on', offline: true }
null '<<my_user_email>>\n' ''
null '<<my_username>>\n' ''
git config is valid
```
(obviously I have edited my github email and username for clarify)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
