### ISSUE TITLE
install.sh doesn't correctly check for Port 80 being used

### ISSUE THREAD

**Issue by DaveSprague** [adafruit/Adafruit-WebIDE#255]
The line in the install.sh script that checks to see if port 80 is already in use is:

if netstat -lnt | awk '$6 == "LISTEN" && $4 ~ ".80"' | grep -q "LISTEN"

but this also returns true if any port starting with 80 (for example, 8080) is in already used.

It should be changed so that the string it checks for is ".80 " rather than ".80"  {with a space after the 80}.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
