### ISSUE TITLE
New Folder when in python in terminal

### ISSUE THREAD

**Issue by magood** [adafruit/Adafruit-WebIDE#257]
I pulled up a terminal window and loaded python.  I was testing some python code interactively and decided I needed a new directory.  After creating the new directory successfully, it pumped a "cd" command into the python window and tried to execute it.  python didn't know what to do with this and thew an exception.
I don't know enough about the system to know what the proper way of dealing with this should be, but it seems like this might be undesirable behavior.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
