### ISSUE TITLE
Can not clone a GIF Bitbucket repo into rPI Web-IDE

### ISSUE THREAD

**Issue by techhead2** [adafruit/Adafruit-WebIDE#261]
I have an existing Bitbucket rPI repo setup with git. When I copy the SSH "link" from Bitbucket's "clone" window into the Web-IDE "clone repo" dialog nothing happens. How can I check what's going on and why it is not working?

Thanks

Joseph

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
