### ISSUE TITLE
Cannot read API key stored in Environment Variables...

### ISSUE THREAD

**Issue by JosephSchafer** [adafruit/Adafruit-WebIDE#263]
I have a bit of simple code that includes the module os.environ.get()  All else equal, the script runs fine when in a terminal via putty and when logged in directly to the computer under my normal username (pi), but not when I am logged into the terminal via the WebIDE under the same username.

I've attached a screencap showing what I see as the same command being run with two different outcomes, based on which terminal I'm running it from. 

Perhaps there's user error here or perhaps calling an os.environ.get() is not supported via the WebIDE for good reason?  I'm too novice to know why that might be...  Humbly submitted... 

![webide environ error](https://cloud.githubusercontent.com/assets/7852270/3234764/26686f50-f0cc-11e3-84ad-e425dd123ad2.png)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
