### ISSUE TITLE
Oops! Google Chrome could not connect to 10.4.104.130

### ISSUE THREAD

**Issue by EE1E** [adafruit/Adafruit-WebIDE#264]
When I installed the i2c, the ide stopped working. I tried to uninstall and reinstall the ide, but I still get this problem.

**Comment by superfluent** [comment]
Same Problem. Would also be interesting to know where the Bitbucket-Data can be changed afterwards, was also suspecting an error there.... but more likely that the I2C caused it to Crash. B+ model

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
