### ISSUE TITLE
Unable to install: "Errors while processing ..."

### ISSUE THREAD

**Issue by clharman** [adafruit/Adafruit-WebIDE#265]
;Beaglebone Black running Debian
I tried the instructions given for Raspberry Pi first (because debian) and then for BBB, received the same errors both times:

update-rc.d: error: insserv rejected the script header
dpkg: error processing restartd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 ntp
 redis-server
 restartd
E: Sub-process /usr/bin/dpkg returned an error code (1)

So that^ was at the end following about a 50 of these:
insserv: Starting led_aging.sh depends on rmnologin and therefore on system facility `$all' which can not be true!

And this a little earlier:
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing redis-server (--configure):
 subprocess installed post-installation script returned error exit status 1

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
