### ISSUE TITLE
Run Button won't work in Chrome

### ISSUE THREAD

**Issue by tfaqir** [adafruit/Adafruit-WebIDE#267]
Dear AdaDev Team,

I'm using Chrome Version 35.0.1916.153 m. First off, I think this is a good effort. I love the IDE layout and functionality. I found the run button doesn't run code. Another thing that would be good to have is a terminate button that knows which pid to kill with GPIO clean perhaps. 

I also found the visiualize sometimes just shows the wait "knight rider thingy" and just sits without doing anything. Mostly it does work but at times it get's stuck and can't start. 

Something else to ponder won't it be better if we had an IDE built using the eclipse framework? I think the look and feel would be great.

Thanks and good luck,

Tahir

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
