### ISSUE TITLE
Set Breakpoint doesn't work in Chrome OSX

### ISSUE THREAD

**Issue by stratfan** [adafruit/Adafruit-WebIDE#270]
Setting a breakpoint by clicking in #6 left most edge of editor window does not work in Chrome or Safari.  Works in Firefox.

Mac OSX Maverick V10.9.4
Google Chrome Version 36.0.1985.143
Safari Version 7.0.6 (9537.78.2)
Firefox 25.0.1

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
