### ISSUE TITLE
Restart [FAIL]

### ISSUE THREAD

**Issue by neilbeforeme** [adafruit/Adafruit-WebIDE#273]
So I had the IDE working all last night, left my raspberry pi turned on all night, and came to it this morning. Couldn't connect to raspberrypi.local (I could last night). Rebooted the pi. Still nothing. Tried the sudo service .... start command - said it's already running -- couldn't connect. Then I tried the restart command - and it fails every time.

What gives? :(

**Comment by agidi** [comment]
i installed all seemed ok, but could no get the editor on the browser, then tried restarting with the same error neilbeforeme reports

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
