### ISSUE TITLE
Can't find Adafruit-WebIDE

### ISSUE THREAD

**Issue by BarnacleBudd** [adafruit/Adafruit-WebIDE#275]
Following tutorial at: https://learn.adafruit.com/webide/use
Just purchased Beaglebone Black from Adafruit

When following the directions, I bring up the internal web page on my bbb and do not see a choice for Adafruit-WebIDE. Instead I see a Cloud 9 IDE.

If I can, I would like to use your IDE.

How do I do that.

Budd

**Comment by Stankman** [comment]
Hi BarnacleBudd.
The BeagleBone has a server already running on port 80 (This is the Cloud 9 IDE you are seeing). If port 80 is already in use, you can change the default port for the WebIDE by following the instructions on the FAQ section of Adafruit's website. https://learn.adafruit.com/webide/faq

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
