### ISSUE TITLE
Can't log into BitBucket account from WebIDE page

### ISSUE THREAD

**Issue by JoshOlds** [adafruit/Adafruit-WebIDE#278]
I am currently trying to use the Adafruit WebIDE while on a corporate network. We have a proxy server for HTTP and HTTPS traffic. I am able to set the Environment Variables http_proxy and HTTPS_PROXY to my proxy server, which allows apt-get and my browser to connect, but the WebIDE does not seem to be able to log into my BitBucket account.

When I click the 'Click here to log into your BitBucket account' button, the page hangs, and nothing happens. When I check the output.log file, I see the error: "error: failed to obtain request token (Error: connect ETIMEDOUT)". I am assuming that the WebIDE is unable to communicate with BitBucket. Is there any way to get the WebIDE to use my corporate proxy?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
