### ISSUE TITLE
Can't scroll terminal window

### ISSUE THREAD

**Issue by umfundi** [adafruit/Adafruit-WebIDE#280]
Chrome on windows 7

terminal text disappears out the bottom of the window.

**Comment by peterrus** [comment]
can confirm. Windows 8 using  Chrome 41.0.2272.101 m

**Comment by peterrus** [comment]
A very dirty workaround would be to execute the following in your browsers javascript console:

jQuery("#editor-output").css('overflow', 'visible')

This will make the console window scrollable, and giving you access to that last few lines that are normally hidden.

**Comment by richjmaynard** [comment]
Same here, Windows 8, Chrome 42.0.2311.135 m

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
