### ISSUE TITLE
Incorrect script run

### ISSUE THREAD

**Issue by umfundi** [adafruit/Adafruit-WebIDE#281]
Changed to a different repository and clicked 'run'

old file was run ( see screenshot ) Im in one file but another is selected to be run.

![error](https://cloud.githubusercontent.com/assets/2498620/5917952/b37b6c18-a61a-11e4-933c-09a3da72ddfd.jpg)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
