### ISSUE TITLE
save button not effective when modifying file

### ISSUE THREAD

**Issue by phil-hx** [adafruit/Adafruit-WebIDE#282]
If i modify a file in the editor and then click on save saved is displayed but neither the local file neither the repository file are updated

**Comment by tomtom23** [comment]
Hi, 
I' have see the same problem on my dev station. it was after remove ntp and work on the network route.
I've install ntp again and now it's work :)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
