### ISSUE TITLE
pi-cam visualizer doesn't seem to be functioning

### ISSUE THREAD

**Issue by grkidwell** [adafruit/Adafruit-WebIDE#284]
hello,

First, thank you for all of your efforts and for such great products.  Whenever I am evangelizing the rPi (which is pretty much all the time), I steer people to Adafruit  as the best resource for both learning and products.

Regarding my bug, I managed to get the debugger working and can run cam.py, but visualizer doesn't appear to work with this program.  I click "visualizer", then after the delay (with bargraph visual), nothing happens.

I am running on an A+.

Have you tested cam.py program on WebIDE?  

https://learn.adafruit.com/diy-wifi-raspberry-pi-touch-cam

BTW:  The visualizer did open up just fine with helloworld.py  (2 print lines).

thank you,
Gary

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
