### ISSUE TITLE
Tons of files just showed up in my project?

### ISSUE THREAD

**Issue by tapnair** [adafruit/Adafruit-WebIDE#285]
Out of nowhere all these files showed up in my project?  Looks like some kind of internet cache files or something?  Did I do something wrong?

These are the files:

05_Utility_Knife-Patrick_2014-Dec-10_07-06-05PM-000_2014_Dec10.png
0f0db7876307790c19e1f91eb9095080-le32d4.cache-4
0f0db7876307790c19e1f91eb9095080-le64.cache-4
12_2014_1Mon_344151.pdf
1487dd4aecf3164c4a11193169052443-le32d4.cache-4
1487dd4aecf3164c4a11193169052443-le64.cache-4
1-7429346630747577735-14884dea29d.asf
25dc7595b658fa46_(1).asc
25dc7595b658fa46.asc
2only.dwg
3042T840.EDRW
3f80be19c668e16fc38439c9c84a1bc7-le64.cache-4
49aa604a5ac92994756d3008e408245c-le32d4.cache-4
49aa604a5ac92994756d3008e408245c-le64.cache-4
4df6625480378f33b6c3f16d6ff1e181-le32d4.cache-4
4df6625480378f33b6c3f16d6ff1e181-le64.cache-4
558352270fb122ca08359d23b5a778d4-le32d4.cache-4
558352270fb122ca08359d23b5a778d4-le64.cache-4
5dc9fcf026e07a49c5f91c19054b9930-le32d4.cache-4
5dc9fcf026e07a49c5f91c19054b9930-le64.cache-4
62205K717.STEP
79652363633577d7d713baab7f54ad8c-le32d4.cache-4
79652363633577d7d713baab7f54ad8c-le64.cache-4
84c0f976e30e948e99073af70f4ae876-le32d4.cache-4
84c0f976e30e948e99073af70f4ae876-le64.cache-4
86SW.bat
8d7231e6733a9725c81b40e9f55f11b1-le32d4.cache-4
93827A211.IGS
a1a78d9c18cd095d3829c724810e6ffb-le32d4.cache-4
a1a78d9c18cd095d3829c724810e6ffb-le64.cache-4
About_Downloads.pdf
act_141013_1036.csv
Adafruit_CharLCD.py
Adafruit_CharLCD.pyc
Additive_mesh.STL
aggregation.dbx
amber_1.jpg
amber2.jpg
amber_3.jpg
Amber4.jpg
ba022efc551c75e21c690774bbcf5304-le32d4.cache-4
ba022efc551c75e21c690774bbcf5304-le64.cache-4
bc06c1eea3e636f72101cafc3fb39508-le32d4.cache-4
bc06c1eea3e636f72101cafc3fb39508-le64.cache-4
bottom.csv
c5f5d66d15c24edc3e863c27139db87e-le32d4.cache-4
c5f5d66d15c24edc3e863c27139db87e-le64.cache-4
CACHEDIR.TAG
carve.csv
CodeDirectory
CodeRequirements
CodeResources
CodeSignature
config.db
config.dbx
config.py
cutting.csv
deleted.dbx
dropbox.pid
ef8951649ecb4e89c7d1ab953911a6bc-le64.cache-4
extension-errors.log
extrusion.csv
f0f76015ef54ea3f0895465d59f141ef-le32d4.cache-4
f0f76015ef54ea3f0895465d59f141ef-le64.cache-4
f22309b238134d3cca63435f528976cd-le32d4.cache-4
f22309b238134d3cca63435f528976cd-le64.cache-4
filecache.dbx
fill.csv
fillet.csv
gdk-pixbuf.loaders
gtkfilechooser.ini
gtk.immodules
gtkrc
history_internal.py
history.py
host.db
hostkeys
info.json
Info.plist
InfoPlist.strings
instance.dbx
known_hosts
lpoptions
meshmixer.ini
milling.csv
notifications.dbx
OctoDisplay.py
OctopiAPI2.py
OctopiAPITest.py
pango.modules
pangorc
PENDING_M5Bv8l
photo.dbx
preface.csv
preferences.xml
recent-files.lst
recently-used.xbel
skeinforge_craft.csv
skeinforge.csv
skeinforge_help.csv
skeinforge_profile.csv
skirt.csv
spyder.ini
spyder.ini.bak
submodules
tclvfse
tclvfse.icns
template.py
temp.py
test.py
TO_HASH_Y1I7F1
tower.csv
unlink.db
UPDATED_mqhHVZ
version.plist
winding.csv
wipe.csv
workingdir

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
