### ISSUE TITLE
I can't uninstall

### ISSUE THREAD

**Issue by ScottieD369** [adafruit/Adafruit-WebIDE#287]
I can't uninstall

**Comment by jwcooper** [comment]
Need a bit more information on why you're unable to uninstall. Do you get a specific error?

Have you run the uninstallation step?
https://github.com/adafruit/Adafruit-WebIDE#uninstallation

You can manually uninstall by following the uninstall script step-by-step:
https://github.com/adafruit/Adafruit-WebIDE/blob/master/scripts/uninstall.sh

**Comment by ScottieD369** [comment]
There are too many links most of them were invalid but I found one that did
work.....grief
Well sorry I am not sure wich one I found that did eventually work.

Yeah sorry I really didn't like that IDE
