### ISSUE TITLE
Node compatibility issue

### ISSUE THREAD

**Issue by jwcooper** [adafruit/Adafruit-WebIDE#289]
Documented and researched here: http://forums.adafruit.com/viewtopic.php?f=8&t=71903&start=30#p369236

**Comment by ddjanic** [comment]
Forbidden

You don't have permission to access /viewtopic.php on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by corzand** [comment]
any chance to get this working with node.js 0.12?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
