### ISSUE TITLE
Sample python scripts preloaded.

### ISSUE THREAD

**Issue by aigarslv** [adafruit/Adafruit-WebIDE#290]
Heya Adafruit - excellent work on IDE! :+1:  I think it would be great to add sample scripts that use GPIO like blinking a LED. Now I realize that this IDE is more for professional programmers, but Visualize feature makes this ideal environment for learning :)

**Comment by beruic** [comment]
Perhaps even a GPIO diagnostics/debugging panel, where you could graphically read the status of the GPIO, and try things out before coding them?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!

**Comment by beruic** [comment]
When about can we expect it to be ready?
And what version will it have?

**Comment by ladyada** [comment]
There's no ETA - subscribe to this repo or the adafruit blog for any release updates :)
