### ISSUE TITLE
My-pi-projects not visible in WebIDE

### ISSUE THREAD

**Issue by MichelReij** [adafruit/Adafruit-WebIDE#292]
After installation of the WebIDE with a fresh bitbucket account, I don't see the "my-pi-projects" folder and I don't have the option to create new files or folders.

<img width="719" alt="schermafdruk 2015-09-20 11 46 07" src="https://cloud.githubusercontent.com/assets/834703/9980140/42473a2c-5f8d-11e5-960b-e01679f3e67d.png">
I suppose I should have set some additional rights somewhere, but I fail to see where. The "my-pi-projects" is present in BitBucket.

**Comment by mapocosm** [comment]
I get the same result, running Chrome and Firefox on OSX. On Windows, Chrome couldn't resolve the URL name, and Firefox converted the name to www.raspberrypi.local and failed. Both computers are on the same wired switch as the Raspberry Pi.

**Comment by codycoder** [comment]
I have the same issue.

**Comment by olliman1** [comment]
Me too

**Comment by sethianuj** [comment]
Solution is:
1. go to your bitbucket account, create a repository there.
2. Then, in your bitbucket,org "repository setup" section, click on "I am starting from scratch" and look at "setup your local directory".
3. Come back to WebIDE, and click on "Terminal" (top middle of WebIDE). In the command, create a new directory (this new directory is the equivalent of "/path/to/your/project"),  execute those git commands.
4. Press the refresh button in top-left of webIDE where the repositories are listed.

**Comment by codycoder** [comment]
I'm setting up another PI soon, I'll try this way next time.  I found a different solution here which also worked.

https://github.com/adafruit/Adafruit-WebIDE/issues/295#issuecomment-173984465

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
