### ISSUE TITLE
indentation error

### ISSUE THREAD

**Issue by mshallop** [adafruit/Adafruit-WebIDE#293]
loading this code: https://github.com/simonmonk/monk_raspberrypi/blob/master/edition_1/04_09_hangman_full_solution.py
in the ide, I get an indentation error at line 15:

  File "hangman.py", line 15  
    while True:  
    ^  
IndentationError: unexpected indent       

Whereas if I just create the same file and run it from the command line, I execute cleanly.

**Comment by tkiener** [comment]
same here. it really strange, as it seems that the editor has problems with pasted code snippets as well as  files that have not been created in webide.

please help as this is a real dealbraker for larger files.
thanks a lot.
bes,
tim

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
