### ISSUE TITLE
OAuth Login Error

### ISSUE THREAD

**Issue by carljdp** [adafruit/Adafruit-WebIDE#294]
Doesn't matter what I try, I can't log into my bitbucket account with raspberrypi.local/login page. I Always get 'an OAuth error occurred' - no error code. Bitbucket acc has been activated/validated from an email I received.. I have double checked my bitbucket key/secret 4  times over, and my date/time is set exactly right for my location and timezone. 

Raspberry Pi 2 / Raspbian Jessie. Locale = en_ZA.UTF-8 (South Africa) - though I have tried en_US but no success. Installed with the curl .. .. | sudo bash command

Please help, Am I doing something wrong?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
