### ISSUE TITLE
Source code disappears 

### ISSUE THREAD

**Issue by CheapB** [adafruit/Adafruit-WebIDE#297]
1) Edit source code
2) Save - get tthe check mark next to the save
3) shortly after I get a "Error: Failure adding file to git"
4) Navigate away from the source code
5) navigate back to the source code
6) source code is gone

On a freshly installed Jessie. Nothing else but WebIde installed. 

Luckily the bitbucket push is somewhat broken as well , so I could get an old version of the source from there...

Is there a way to downgrade? 0.3.12 is so fragile..

**Comment by M-Klitgaard** [comment]
Same here... has been struggeling a lot with the new release of Adafruit whish I could go back to the stable release

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
