### ISSUE TITLE
Unable to clone projects or changes

### ISSUE THREAD

**Issue by matt65** [adafruit/Adafruit-WebIDE#299]
On my Raspberry Pi, using a fresh install of Raspbian Jessie and with only WebIDE installed after installing WebIDE and logging into my BitBucket account only the Adafruit-Raspberry-Pi-Python-Code repository is available.

I attempted to clone the my-pi-projects from my BitBucket account, after inserting the SSH URL into the WebIDE clone repository pop-up I am getting the error:
Cloning into 'my-pi-projects'... Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

![image](https://cloud.githubusercontent.com/assets/5351056/11653741/3887a20a-9df0-11e5-979b-b7d3218a7ccc.png)

If I was to follow the BitBucket steps for cloning via a terminal window an empty repository and committing an empty txt file, the file is pushed and that repository is then available within WebIDE.  If I was to edit the file and click save WebIDE is reporting the file has been saved however it won't upload the changes to BB.

Eventually, after saving changes to a file, I will get the error message Error: Failure pushing code to remote repository
![image](https://cloud.githubusercontent.com/assets/5351056/11653809/c74eeb06-9df0-11e5-8a9f-153c26f8bab6.png)

I have changed the owner on the new repository (was previously root:root) so that it is:
drwxr-xr-x  4 webide webide 4096 Dec  8 10:18 PiCar

This matches the existing repositories permissions.

I am running WebIDE v0.3.12, I have done an apt-get update/install/upgrade, installed npm and installed cookie (seen that referenced in a issue the other day).

Can anyone advise how I can resolve this or possibly log files which might give further information?

Your help is greatly appreciated.

**Comment by tkiener** [comment]
same problem here...

**Comment by olliman1** [comment]
Me too

**Comment by CheapB** [comment]
me too

**Comment by cattnb** [comment]
Me too

**Comment by phoniclynx** [comment]
Me too !!

**Comment by CheapB** [comment]
While I had to reinstall to get rid of this issue - there are some other error messages similar to this you will see with an expanded environment, so make sure you are not out of space

**Comment by phoniclynx** [comment]
I've done a reinstall hoping it would fix it.. but I'm still getting those same errors.

**Comment by CayenneSF** [comment]
Same problem here....

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
