### ISSUE TITLE
desinstaller ruins PI

### ISSUE THREAD

**Issue by gbaumgart** [adafruit/Adafruit-WebIDE#300]
hi,
i followed the uninstall procedure and afterwards very important packages got deinstalled: git, node, some libraries needed for omxplayer and some apache modules. It was no messy afterwards that i had to re-install all over again. thanks for that!

**Comment by jwcooper** [comment]
How did you uninstall the WebIDE? The uninstaller specifically does not uninstall git and node or any packages due to your exact reason. The end of the installer mentions this here: https://github.com/adafruit/Adafruit-WebIDE/blob/master/scripts/uninstall.sh#L55
