### ISSUE TITLE
Find the webIDE after restarting PI

### ISSUE THREAD

**Issue by Meresmata** [adafruit/Adafruit-WebIDE#301]
Hi,

 after I installed the IDE on my Paspberry PI (B) I was able to work normal all seamed to work perfect. After I quarter of an hour (or so) it stopped working (lost connection?, don't know). I rebooted the pi, but neighter could I find the IDE under the IP of the Pi anmore, nore was I able to reach it under raspberrypi.local. 
I rebooted several times, did update and upgrade via ssh.

**Comment by Jlaird** [comment]
I am having the same issue.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
