### ISSUE TITLE
Error: Failure updating from remote repository when using 2 RPIs

### ISSUE THREAD

**Issue by CheapB** [adafruit/Adafruit-WebIDE#302]
I have 2 RPIs looign in to the same bitbucket account.bot version 3.12. one is working perfectly - the other APPEARS to work perfectly until i select update repository where I get "Error: Failure updating from remote repository"

The local files front he 2nd RPI are not updated to the server

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
