### ISSUE TITLE
Output screen goes off screen

### ISSUE THREAD

**Issue by phoniclynx** [adafruit/Adafruit-WebIDE#304]
After running code a few times the console screen goes below the visible part of the screen. and you can not view any errors or outputs after a short time. No scroll bar to go down and the scroll wheel doesn't scroll below a few lines. Only option is to type clear and re run your code.

**Comment by phoniclynx** [comment]
Noticed this is happening because the folder I created had a hyphen in it. This was causing the console to do a carriage return (\n) after the hyphen. So it was always 1 line out of sync, meaning you can not see it.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
