### ISSUE TITLE
Won't progress from setup page

### ISSUE THREAD

**Issue by Jwboucher94** [adafruit/Adafruit-WebIDE#305]
So my problem is that, everything shows up fine and it's working from raspberrypi.local, but when I type in my bitbucket info, it just refreshes the screen instead of moving forward. Any suggestions? where would an error log be located? I can't seem to find one.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
