### ISSUE TITLE
Adafruit-WebIDE No connection with Chome & Firefox

### ISSUE THREAD

**Issue by clewbay** [adafruit/Adafruit-WebIDE#308]
Hi there,
I was a bit fed up writing python with SSH + VI or NANO or reformating code with dos2unix after using IDLE on Windows. So I started to install adafruit-webide on my Raspberry...
Everything seems ok on the raspberry: 
ping 192.168.0.30 is fine
"adafruit-webide is running"
No way to log onto my local raspi address: http://192.168.0.30 : ERR_CONNECTION_REFUSED
with Chrome and Firefox with my Windows 10 LAPTOP (+ Norton Security)
with Chrome and Firefox with my old Windows XP tower (+ Zone Alarm)
and with Iceweasel with my Debian  8 laptop.

Should I do some config on the Raspberry?

Thanks for your help.
Regards.
M.P.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
