### ISSUE TITLE
DEBUG mode not working

### ISSUE THREAD

**Issue by pagaille** [adafruit/Adafruit-WebIDE#309]
Hi,

I tried to install and reinstall the WebIDE by multiple ways (automatic, scripted, manual) but without result : **everything works correctly**... except the Debug mode ! As soon as I click one of the buttons in debug mode, the cursor changes to a never ending blue spinning wheel (OS/X client, Chrome or Safari).

I don't know where to start to debug this issue. Any pointer to the right direction ? I'm running the latest Jessie image and latest webIDE on a Pi 3B v1.2

Thanks, this IDE looks really promising !

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
