### ISSUE TITLE
Incomplete list of existing files in directory when symbolic link exists

### ISSUE THREAD

**Issue by gigagarfield** [adafruit/Adafruit-WebIDE#310]
In case one of the files in the directory shown in the file list is a symbolic link (created manually via terminal) the list of files is not displayed completely but stops at the symbolic link. So if there is a file called "link.lnk" only files up to the letter "k" are displayed. The rest is missing and only reappears if the symbolic link is deleted. Observed on a raspberry 2 running adafruit webide on Raspbian Jessie.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
