### ISSUE TITLE
WebIDE not working on Pi 2 model B

### ISSUE THREAD

**Issue by langdons** [adafruit/Adafruit-WebIDE#311]
I had the WebIDE (unknown version) working on my Pi 2 B (running Rasbian - setup 18th months ago).  I just went back to the project today and noticed that there was an update available (through the WebIDE interface).  I ran the update, but it didn't complete and the WebIDE then didn't work.

So I uninstalled the WebIDE and re-installed it.  I tried both the deb package and install.sh.  Both installs ran fine and completed successfully.  However I cannot connect to the WebIDE from my laptop, or from the Pi itself.

When I run:

`sudo service adafruit-webide.sh stop`

I get no response (or error)

Running start and restart gives the following response:

`pi@crusty ~ $ sudo service adafruit-webide.sh start
[....]   --->  Daemon already running Adafruit WebIDE server: adafruit-webide

pi@crusty ~ $ sudo service adafruit-webide.sh restart
[FAIL] Restarting Adafruit WebIDE server: adafruit-webide failed!`

Checking Top on the Pi the WebIDE process does not show up - except for a second on two occasions, then it disappears again.

So I am stumped.  It's running, but can't be restarted.  It can't be stopped.  And I can't access it.

Does anyone have a suggestion of what might be wrong?

Thanks in advance for any advice.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
