### ISSUE TITLE
Terminal Window Won't Scroll

### ISSUE THREAD

**Issue by msakkas** [adafruit/Adafruit-WebIDE#313]

**Comment by spierepf** [comment]
I'm having this issue also. I believe it has to do with changing the font size on the "Edit your settings" screen.

The terminal screen appears to limit itself to a certain number of columns. (I'm guessing 80), and then doesn't count rows correctly.

Let me know if you need more detail. I really love this project.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
