### ISSUE TITLE
Will not commit/push git

### ISSUE THREAD

**Issue by aplocher** [adafruit/Adafruit-WebIDE#314]
Very little information is provided.  Here is what the UI shows:

![image](https://cloud.githubusercontent.com/assets/1132447/21851980/405a39f0-d7c6-11e6-9160-aa959d5fa398.png)

I don't see any meaningful logging.  It created the repo at BitBucket just fine, but hasn't checked anything into it.  

Also, the javascript console has this:

![image](https://cloud.githubusercontent.com/assets/1132447/21852111/aa7b5602-d7c6-11e6-8eb7-544c4496e5cd.png)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
