### ISSUE TITLE
"Clone Repository Modal" upper right X button not working

### ISSUE THREAD

**Issue by CyrilAntoni** [adafruit/Adafruit-WebIDE#318]
![clone-repository-modal-x-button-not-working](https://cloud.githubusercontent.com/assets/13135150/26561562/b1b485fe-44bf-11e7-9578-a31f460afd3b.png)

The "x" button doesn't close the modal.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
