### ISSUE TITLE
Can't connect from browser

### ISSUE THREAD

**Issue by jtiscione** [adafruit/Adafruit-WebIDE#319]
I ran webide.sh to install on a Raspberry pi 3, and it generated the following output:

**** Starting the server...(please wait) ****
**** The Adafruit WebIDE is installed and running! ****
**** Commands: sudo service adafruit-webide.sh {start,stop,restart} ****
**** Navigate to http://pi3.local to use the WebIDE

The Raspberry Pi refuses all browser connections, at least on port 80.

How do I uninstall this thing?

**Comment by CheapB** [comment]
Are you on Stretch  or Jessie? I cant get this to work on a clean Stretch install but got the same issues you describe. works well under Jessie

**Comment by stemalda** [comment]
I have the same problem running Stretch ....

**Comment by arcasoy** [comment]
Did anyone find a fix to this? Whenever I try to connect it does the same thing, not picking up the connection at all. What to do? I am also using UbuntuMATE

**Comment by jwcooper** [comment]
The webide is being worked on in a 'rework' branch (pull request above). We're simplifying the webide, and hoping it will be easier to support in the future. You could try the new branch as we work on it.

Thanks!
