### ISSUE TITLE
Don't know if this is a bug, but I don't find help elsewhere

### ISSUE THREAD

**Issue by SteveRMann** [adafruit/Adafruit-WebIDE#320]
My script reads data from a text file, but when running the visualizer, I get this error:
'IOError: file() constructor not accessible in restricted mode'

Am I simply not understanding the visualizer?

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
