### ISSUE TITLE
BitBucket Account info - can't find Account / OAuth 

### ISSUE THREAD

**Issue by tgmcnaughton** [adafruit/Adafruit-WebIDE#321]
Trying to follow your guide re: getting access codes from BitBucket.  
I'm trying:
https://bitbucket.org/dashboard/overview
Their site is QUITE different from your screenshots. I can't even find where to get my account info.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
