### ISSUE TITLE
No "Integration" capability in new BitBucket UI 

### ISSUE THREAD

**Issue by cyberchucktx** [adafruit/Adafruit-WebIDE#322]
While trying to follow the Adafruit article on Adafruit IDE ("Getting Started" at https://learn.adafruit.com/webide/getting-started ) the Bitbucket UI is different from what's shown. I don't see any way to add the RPI repository.

Could you please update or correct the tutorial? 

Thanks,

**Comment by cyberchucktx** [comment]
I may have answered my own question just now; the new UI has a section on "OAuth" which includes the "Add Consumer" button.

**Comment by cyberchucktx** [comment]
Please correct the tutorial screenshots for BitBucket though (please!)

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
