### ISSUE TITLE
WebIDE seems not connected to BitBucket

### ISSUE THREAD

**Issue by Semmidemmi263** [adafruit/Adafruit-WebIDE#323]
Hi!
After installing the WebIDE on my raspberry pi zero W and signing up for the BitBucket repository, connecting the two using OAuth and providing the necessary keys, I can open the WebIDE programming page in firefox. Neither is it creating any "my projects"-folder, nor am I able to create new files or subfolders. There is an "EACCES"-error when I try. In the right upper bar, it says "connected", but when it tries to commit, it changes to a red "error comitting ...". 
My proposition is that WebIDE is running and I can connect to my raspberry pi through the web browser, but there is no connection to the git repository. In the OAuth part of the settings in bitbucket, the raspberry pi is listed in authorized devices and consumers.

What am I doing wrong?

**Comment by eholmes** [comment]
I had the same issue.  I logged out of the webIDE and logged back in and it worked for me.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
