### ISSUE TITLE
Deprecated reference to Jade and Connection

### ISSUE THREAD

**Issue by linuxweenie** [adafruit/Adafruit-WebIDE#324]
Encountered a deprecated warning when the npm install was run:

pi@raspberrypitest:~/Adafruit-WebIDE $ npm install
npm WARN deprecated jade@0.28.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated connect@2.7.3: connect 2.x series is deprecated
npm WARN deprecated connect@2.7.2: connect 2.x series is deprecated
|

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
