### ISSUE TITLE
Installation issue, with temporary fix(?)

### ISSUE THREAD

**Issue by JoeSpinogatti** [adafruit/Adafruit-WebIDE#326]
Sorry if this isn't the right place to put this, but just wanted to add it to the official list in case it's helpful to anyone else after a couple hours of searching. 

I tried to install and uninstall the WebIDE multiple times and kept getting an error in the browser that I couldn't connect (conenction refused) no matter what port it was on. Tried both manual and script installations - no dice. 

Finally reinstalled from the script and followed the suggestion from the following forum to get it to work. Scroll down to post by mfripp with commands.

https://forums.adafruit.com/viewtopic.php?f=19&t=85839

**Comment by JoeSpinogatti** [comment]
Update: After trying to work with this for a little bit, it gets things to run/install, but it is essentially unusable in this state.

**Comment by CheapB** [comment]
Are you on Stretch or Jessie?

**Comment by jwcooper** [comment]
We're working on simplifying the webide. There is a beta branch you can try out, if you want to tinker with it. Most likely you'll run into bugs, but it should be in a more usable state than the master branch is now.
