### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by colinluthier** [adafruit/Adafruit-WebIDE#332]
I am trying to run an example program from your site. I really did not want to use the IDE but I can't seem to make it work with an old library (MCP23017). So, I installed your IDE. The instructions say there should be the libraries cloned to my left. I can not see them. The instructions say I should have a terminal. I can hit the button but I can not click into the window that splits onto the bottom half of the screen. The instructions say there should be a run button on my python code but it is not there. I am running a macOS Sierra and Chrome.

**Comment by jwcooper** [comment]
Do you have a link to that guide? We no longer have a single location for all python libraries and do not clone those in this webide any longer.

It looks like this could be what you're looking for:
https://github.com/adafruit/Adafruit_Python_GPIO/blob/master/Adafruit_GPIO/MCP230xx.py
