### ISSUE TITLE
problem installing on pi zero w

### ISSUE THREAD

**Issue by sleepyb** [adafruit/Adafruit-WebIDE#338]
when using script 

    curl https://raw.githubusercontent.com/adafruit/Adafruit-WebIDE/master/scripts/install.sh | sudo sh
  
i get error 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3776  100  3776    0     0   8160      0 --:--:-- --:--:-- --:--:--  8190
false
**** Downloading the latest version of the WebIDE ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131    0   131    0     0    120      0 --:--:--  0:00:01 --:--:--   120
100 2379k    0 2379k    0     0   465k      0 --:--:--  0:00:05 --:--:--  746k
**** Installing required libraries ****
**** (nodejs-legacy npm git i2c-tools python-smbus ntp libkrb5-dev) ****

**Comment by jwcooper** [comment]
The Pi Zero W is unsupported at this time due to it being on the ARMv6 architecture. As of now, we only support the Pi 2 and 3 due to it greatly simplifying installation and support. We do accept pull requests though!

**Comment by dylanpoll** [comment]
well, its a "quick fix", and I am sure there are bugs with doing things in this ultra lazy fashion but....
I made a shell script that does this, you can just do it line by line tho.

`#cd
#wget https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-armv6l.tar.xz
#tar -xvf node-v8.11.3-linux-armv6l.tar.xz
#cd node-v8.11.3-linux-armv6l
#sudo cp -R * /usr/local/
#git clone git://github.com/adafruit/Adafruit-WebIDE.git
#cd Adafruit-WebIDE
#mkdir tmp
#npm config set tmp tmp
#npm install
#editor config/config.js
#nodejs server.js`

credit to:
https://raspberry-valley.azurewebsites.net/Adafruit-webIDE/
https://github.com/adafruit/Adafruit-WebIDE
https://warlord0blog.wordpress.com/2018/06/27/node-js-v8-on-raspberry-pi-zero/
