### ISSUE TITLE
Linking to Bitbucket is unclear or not working

### ISSUE THREAD

**Issue by CheapB** [adafruit/Adafruit-WebIDE#340]
I have read bitbucket integration is now manual and that is fine but the documentation does not mention anything about how to set it up. I have a couple of well working RPIs and i just did a new install and I cant figure out to connect to bitBucket. After installation it ask for Name and email address and nothing else. It does not clone the adafruit repository and there is no obvious way get the link to BitBucket to work

**Comment by jwcooper** [comment]
You would setup bitbucket as you would on any pc through a terminal. You'll need your ssh key, etc. The only thing you don't need to do is install git, as that's already included. Once it's setup, you can clone repositories in the webide as usual.

https://confluence.atlassian.com/bitbucket/set-up-an-ssh-key-728138079.html
