### ISSUE TITLE
add back pop-out terminal window 

### ISSUE THREAD

**Issue by papple** [adafruit/Adafruit-WebIDE#87]
I like the new inline terminal but sometimes it's great having multiple pop-out terminals like the previous versions (saves using putty all the time).  Could you add a 'Pop-out Terminal' button and add the removed code back in?

Thanks,
Paul

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
