### ISSUE TITLE
Anyone on LAN can get root access.

### ISSUE THREAD

**Issue by wyojustin** [adafruit/Adafruit-WebIDE#99]
Problem:  
Anyone with a bit bucket account on LAN can obtain root access.  

Potential Fix: Add local log in step to prevent undesirable access.  Add user repos under
/usr/share/adafruit/webide/repositories/USER/my-pi-projects

Discussion:
Let me start by saying I LOVE WEBIDE!!!  I am amazed at how far along it is already.  Thank you for putting this together!!

It would be great to develop apps on the pi from anywhere.  WyoLum is a distributed hackerspace and we need to collaborate with members from all over the world.  This feature would enable us to do that and be awesome and well used.

Justin

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
